"""Thread-safe concurrency and deduplication locks for wiki-video-pipeline."""

from __future__ import annotations

import logging
import threading
from contextlib import contextmanager
from typing import Generator

from src.db import store

logger = logging.getLogger(__name__)


class ConcurrencyConflictError(RuntimeError):
    """Raised when an operation cannot proceed because an identical topic is active."""


class TopicLockManager:
    """Thread-safe lock manager for in-flight topic generations and uploads."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._active_topic_keys: set[str] = set()
        self._active_wiki_keys: set[str] = set()
        self._active_upload_run_ids: set[int] = set()

    @contextmanager
    def lock_topic(self, topic: str, fmt: str = "short") -> Generator[str, None, None]:
        """Acquire in-flight execution lock for a topic key."""
        norm = store.normalize_topic_key(topic)
        key = f"{fmt}:{norm}" if norm else f"{fmt}:{topic.strip().lower()}"
        with self._lock:
            if key in self._active_topic_keys:
                raise ConcurrencyConflictError(
                    f"Topic '{topic}' is already actively generating or queued"
                )
            self._active_topic_keys.add(key)
        try:
            yield key
        finally:
            with self._lock:
                self._active_topic_keys.discard(key)

    @contextmanager
    def lock_wiki(self, wiki_title: str) -> Generator[str, None, None]:
        """Acquire lock for a resolved Wikipedia canonical title."""
        norm = store.normalize_topic_key(wiki_title)
        if not norm:
            yield ""
            return
        with self._lock:
            if norm in self._active_wiki_keys:
                raise ConcurrencyConflictError(
                    f"Canonical article '{wiki_title}' is currently being generated by another task"
                )
            self._active_wiki_keys.add(norm)
        try:
            yield norm
        finally:
            with self._lock:
                self._active_wiki_keys.discard(norm)

    @contextmanager
    def lock_upload(self, run_id: int) -> Generator[int, None, None]:
        """Acquire upload lock for a specific run ID."""
        with self._lock:
            if run_id in self._active_upload_run_ids:
                raise ConcurrencyConflictError(f"Upload already in progress for run #{run_id}")
            self._active_upload_run_ids.add(run_id)
        try:
            yield run_id
        finally:
            with self._lock:
                self._active_upload_run_ids.discard(run_id)

    def is_topic_locked(self, topic: str, fmt: str = "short") -> bool:
        norm = store.normalize_topic_key(topic)
        key = f"{fmt}:{norm}" if norm else f"{fmt}:{topic.strip().lower()}"
        with self._lock:
            return key in self._active_topic_keys

    def is_wiki_locked(self, wiki_title: str) -> bool:
        norm = store.normalize_topic_key(wiki_title)
        with self._lock:
            return bool(norm and norm in self._active_wiki_keys)

    def is_upload_locked(self, run_id: int) -> bool:
        with self._lock:
            return run_id in self._active_upload_run_ids


topic_locks = TopicLockManager()
